### PR TITLE
Fix issue when using strict types

### PR DESCRIPTION
**Pull request by chrisandchris**
When using PHP 7 and strict types, the array filter used when creating an array from the `Message` will throw an error when any containing data element is an array.

By adding a test `is_string` and comparing also using `empty`, this will be prevented.

### CODE REVIEW

**Comment by bzikarsky** [comment]
You are correct. Thanks! :smile: Can you fix the conflict (Sorry, I caused it...) and then I'll merge?

**Comment by chrisandchris** [comment]
I fixed the issue already (see changes) by upgrading the array_filter() call.

**Comment by bzikarsky** [comment]
I'm really sorry that this idled so long. I must have missed your followup comment. I'll merge the changes now

**Comment by chrisandchris** [comment]
That's fine by me - thanks for merging!

**Pull request merged**
