### PR TITLE
Update comments

### PR DESCRIPTION
**Pull request by betweenbrain**
Fixes a typo in the UDP transport comment and makes it more succinct to fit on one line before wrapping.

### CODE REVIEW

**Comment by bzikarsky** [comment]
Sorry, but the line now is above 120 (preferred 80) characters. That's also the reason Scrutinizer complains: https://scrutinizer-ci.com/g/bzikarsky/gelf-php/inspections/50fb0d04-a4f3-4651-809f-8b844678db5c/issues/files/examples/advanced.php?status=new&orderField=path&order=asc&honorSelectedPaths=0

I'm happy to merge if you fix this :smile:, thanks!

**Comment by bzikarsky** [comment]
ping @betweenbrain

**Comment by betweenbrain** [comment]
Thanks for the ping, I missed your previous comment. Will try to fix ASAP.

**Comment by bzikarsky** [comment]
Squashed your commits and pushed to master.

**Pull request closed without merging**
