### PR TITLE
fix compare (by bytes) string length in SteamSocketClient

### PR DESCRIPTION
**Pull request by EgorShevelev**

### CODE REVIEW

**Comment by bzikarsky** [comment]
Sorry, but this PR does not make any sense in my opinion: What do you want to accomplish by converting the bytes in a hexadecimal representation and dividing that by 2?

http://php.net/strlen returns the byte-length straight up.

**Comment by casskir** [comment]
When using UdpTransport writing to the socket (default value mbstring.func_overload=2 and default charset is UTF-8) the number of bytes written is not equal to the number of bytes in the string. This is due to the fact that mb_strlen function does not correctly determine the length of the binary string.

**Comment by bzikarsky** [comment]
Yes, but problems such as this are exactly the tradeoff of using a behaviour-changing configuration like `mbstring.func_overload`. The"fix" is a hack around this edge-case, caused by the configuration.

`strlen` *is* the PHP function to determine byte-length. Changing this, leads to undefined behaviour with many large projects out there. All of them rely on strlen as a byte-length function:

- ReactPHP: https://github.com/search?q=org%3Areactphp+strlen&type=Code
- Symfony: https://github.com/symfony/symfony/blob/ac3eb5d91f54ab4fb44e84b66b7d24cd81d15e72/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php#L636
- Zend: https://github.com/zendframework/zend-http/blob/98b1cac0bc7a91497c5898184281abcd0e24c8d6/src/Header/AbstractAccept.php#L440
- etc.

Even in this project multiple functions would need to be changed:
- https://github.com/bzikarsky/gelf-php/blob/bc1175a5b40f585e69a017647286d84211e82544/src/Gelf/Transport/UdpTransport.php#L84
- https://github.com/bzikarsky/gelf-php/blob/c87c596f0b8aba9592c7b66ba1af603d3b139f5b/src/Gelf/Transport/HttpTransport.php#L165
- https://github.com/bzikarsky/gelf-php/blob/f25629129f0b8e2b2556894a54f8127b1e19392b/src/Gelf/Transport/StreamSocketClient.php#L204

I'm leaning very strongly to not changing this.

**Comment by bzikarsky** [comment]
To get a broader opinion I'll linked the discussion on reddit: https://www.reddit.com/r/PHP/comments/5dmllb/request_for_opionions_handling_mbstringfunc/

**Comment by bzikarsky** [comment]
The discussion confirmed my general feeling against this "hack". I will not merge this PR, instead I will throw an exception if `mbstring.func_overload` is set.
´
Thank you for contributing and pointing me towards this possible failure.

**Pull request closed without merging**
