### PR TITLE
Missing return in setVersion()

### PR DESCRIPTION
**Pull request by Gummibeer**
There was a missing return in the setVersion() function.

### CODE REVIEW

**Comment by bzikarsky** [comment]
ping @Gummibeer :smile:

**Comment by bzikarsky** [comment]
I'll add the tests myself :smiley:

**Comment by Gummibeer** [comment]
I'm sorry - I was ill for a long time and not really back again. :/

**Comment by bzikarsky** [comment]
Don't worry :wink: -- Get well soon!

**Pull request merged**
