### PR TITLE
Replaced using strlen function on Binary::safeStrlen (package paragonie/constant_time_encoding)

### PR DESCRIPTION
**Pull request by olegpro**
This allows us to work the same way with the option set mbstring.func_overload.

### CODE REVIEW

**Comment by bzikarsky** [comment]
While I like your proposition, there is a problem with it: There is no compatibility <PHP7, we can't break this

Can we work around this?

**Comment by olegpro** [comment]
@bzikarsky fixed. Added support for php 5.

**Comment by miolae** [comment]
@bzikarsky, hi! Explain me, please, why don't you support `mbstring.func_overload` now (version 1.5.5)?
Thanks in advance.

**Comment by miolae** [comment]
I mean the error 
```[UnexpectedValueException] 
Overloading of string functions using mbstring.func_overload is not supported by this library. (0)
vendor/graylog2/gelf-php/src/check_technical_requirements.php:14``

**Comment by miolae** [comment]
Oh, now I see that 1.5.5 is released on June 2017.
When will we see a new one? :)

**Comment by Tobion** [comment]
IMO this should be reverted. `mbstring.func_overload` is deprecated since PHP 7.2 so there should not be a workaround for something that is already going to be removed.

Also the dependency it pulls (paragonie/constant_time_encoding) is about a constant time encoding for security. This is not relevant here at all.

**Comment by miolae** [comment]
@Tobion I still have some projects on php5.6 which are not going to upgrade their environment. And those projects won't work without `func_overload`. So my IMHO is that your words about "is going to be removed" are too hasty. Because its really going to be removed, but only from *the future versuons of the language*, not from production.

**Comment by bzikarsky** [comment]
@Tobion You are correct. When I was working through a pile of old PRs and commits this one slipped thru. I'm pretty much of your opinion that "func_overload" is bad by design and should not be supported. I think I rejected a PR once which tried to manually handle this setting in php-gelf's source. On the positive side: It's hidden behind library code.

@miolae While I agree with you on "things being in production", gelf-php made a point of not supporting this feature. So this argument does not really count.

So, therefore: I'll keep the dependency and the (accidental) support in the 1.x releases. I kind of expect 1.6.x (maybe even 1.6.x) to be the last release. I'll drop the support in 2.x.

**Pull request merged**
