### PR TITLE
Optimize Message::logLevelToSyslog

### PR DESCRIPTION
**Pull request by Cosmologist**

### CODE REVIEW

**Comment by bzikarsky** [comment]
Hello there,

while this might be slightly faster: Did you run in performance trouble with this?

And  I have a slight coding-style issue: I'm not so fond of assignments in a condition clause, maybe you can pull out the assignment to a separate line.

Thanks!

**Comment by Gummibeer** [comment]
wouldn't a switch-case be the fastest solution!?

**Comment by bzikarsky** [comment]
Oh well. Probably. My original approach is O(n) (but let's not forget this is an array of < 10 elements...) because of the array_flick. The isset()-lookup should be O(1) and with an added "cache" of the flicked array pretty much similar to a switch/case or chained if/else. Anyways...

...I think this is quite the micro-optimization, and keeping the code simple seemed like the appropriate goal in this case. But go ahead, knock yourself out microbenching the hell out of this 😉

**Comment by Gummibeer** [comment]
I also think that the server or webapp won't crash or run in timeouts cause of an array_flip.^^
But the most performant would be a switch-case (in theory) with enabled op-cache and so on we talk about some millionstel (or whatever is it called) second.

**Comment by Cosmologist** [comment]
Firstly, it's more readable code
Secondly - yes, it's more [faster](https://3v4l.org/vv0U8)

**Comment by bzikarsky** [comment]
That's what I said...It may be faster, but it's still a micro-optimization anyway: We are talking about a 200ns-difference on a modern PHP version.

I'm willing to merge this, if you pull the assignment out of the if-clause. Assignments in conditions are bad style in my opinion. There are some applications in (while-)loops, but this should be

```php
$syslogLevel = array_search($level, self::$psrLevels)
if (false !== $syslogLevel) {
    return $syslogLevel;
}
```

**Pull request merged**
